
[workspace]
resolver = '2'
members = [
	'apps/api',
	'libs/prisma_generator',
	'libs/prisma_client',
	'libs/authentication_cookie',
	'libs/authentication_middleware',
]

[workspace.dependencies]
actix-web = '4.5.1'
futures-util = '0.3.30'

[profile.release]
lto = true
