
[workspace]
resolver = '2'
members = [
	'apps/api',
	'libs/prisma_generator',
	'libs/prisma_client',
	'libs/authentication_cookie',
]

[profile.release]
lto = true

[workspace.dependencies]
actix-web = "4.5.1"
